# 🛠 Exercises

In [1]:
# prerequisite (load tensorflow)
import tensorflow as tf

### 1. Create a vector, scalar, matrix, and tensor with values of your choosing using `tf.constant()`.

In [26]:
# scalar
a_scalar = tf.constant(1)

# vector
a_vector = tf.constant([1, 2, 3, 4])

# matrix
a_matrix = tf.constant([[1, 2],
                        [3, 4]])

# tensor
a_tensor = tf.constant([[[1, 2],
                         [3, 4]]])

### 2. Find the shape, rank, and size of the tensors you created in 1.

In [27]:
# scalar's shape, rank, and size
a_scalar.shape, a_scalar.ndim, tf.size(a_scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [8]:
# vector's shape, rank, and size
a_vector.shape, a_vector.ndim, tf.size(a_vector)

(TensorShape([4]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [9]:
# matrix's shape, rank, and size
a_matrix.shape, a_matrix.ndim, tf.size(a_matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [10]:
# tensor's shape, rank, and size
a_tensor.shape, a_tensor.ndim, tf.size(a_tensor)

(TensorShape([1, 2, 2]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [14]:
random = tf.random.Generator.from_seed(42)
random_a = random.normal(shape = (5, 300))
random_b = random.normal(shape = (5, 300))
random_a, random_b

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702,  0.07595026, ..., -1.071834  ,
         -1.0722276 , -0.00586287],
        [-0.88051033, -0.32426047, -2.4847078 , ...,  0.16512105,
          1.155565  , -0.10707551],
        [-1.5306779 , -0.86202925, -0.16359143, ...,  0.34288085,
          1.216793  , -1.24293   ],
        [ 0.84324265, -0.23379943,  0.4276398 , ..., -1.0428714 ,
         -0.73970354,  0.0177109 ],
        [ 0.04888754, -0.66408694, -1.787366  , ...,  0.1947453 ,
          0.5656089 ,  0.18439196]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[-0.8154969 ,  0.26007915,  0.7127341 , ..., -0.11047905,
          0.31384605,  0.04477395],
        [-2.1549582 , -1.4071537 ,  0.9872657 , ..., -0.80686337,
          1.1725203 ,  0.5656763 ],
        [ 1.4838083 , -0.548992  ,  0.591757  , ..., -0.26100376,
         -0.83735627,  0.08331773],
        [-0.8043715 ,  0.18194008, -0.63925874, ...,  1.9768345 

### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [16]:
tf.matmul(random_a, random_b, transpose_b = True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -8.546614  , -40.451714  ,  -1.2857952 ,  12.056652  ,
         17.793924  ],
       [  3.4720552 , -18.612564  ,  19.392818  ,   4.541705  ,
          0.50874996],
       [-26.502096  ,  26.028545  , -32.437515  , -13.962518  ,
          4.268737  ],
       [-34.87094   ,  -4.182907  , -26.432697  ,  18.378395  ,
        -31.007895  ],
       [ -0.47158718,  10.985781  ,  15.900086  , -34.34557   ,
         -2.5210218 ]], dtype=float32)>

### 5. Multiply the two tensors you created in 3 using dot product.

In [19]:
tf.tensordot(random_a, tf.transpose(random_b), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -8.546614  , -40.451714  ,  -1.2857952 ,  12.056652  ,
         17.793924  ],
       [  3.4720552 , -18.612564  ,  19.392818  ,   4.541705  ,
          0.50874996],
       [-26.502096  ,  26.028545  , -32.437515  , -13.962518  ,
          4.268737  ],
       [-34.87094   ,  -4.182907  , -26.432697  ,  18.378395  ,
        -31.007895  ],
       [ -0.47158718,  10.985781  ,  15.900086  , -34.34557   ,
         -2.5210218 ]], dtype=float32)>

### 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [20]:
random = tf.random.Generator.from_seed(42)
random_c = random.normal(shape = (224, 224, 3))
random_c

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        ...,
        [ 0.07099114, -0.5095768 ,  0.3482001 ],
        [ 0.15985982, -1.9042184 ,  0.9690504 ],
        [ 0.16251186, -0.07330752, -0.360591  ]],

       [[ 0.18739441, -0.73353654,  1.2104433 ],
        [ 1.5603006 , -0.48115277,  0.6335167 ],
        [-0.5612103 ,  0.06994031,  1.6807095 ],
        ...,
        [-1.9460293 , -0.7977275 ,  0.03092833],
        [ 0.8297488 ,  0.12179119,  1.0506107 ],
        [-1.3097638 ,  0.92536974, -1.1787732 ]],

       [[-0.21711822, -0.73974085, -1.3077081 ],
        [-0.7502274 , -0.37715855, -0.30130875],
        [ 1.0943383 ,  0.255803  ,  0.8011465 ],
        ...,
        [-0.32833767, -0.7794747 ,  0.20049338],
        [-0.09002841,  0.07243238, -0.81940895],
        [ 0.3171264 , -1.6143695 , -1.6824651 ]],

       ...,

     

### 7. Find the min and max values of the tensor you created in 6.

In [22]:
tf.reduce_min(random_c), tf.reduce_max(random_c)

(<tf.Tensor: shape=(), dtype=float32, numpy=-4.848316>,
 <tf.Tensor: shape=(), dtype=float32, numpy=4.4032865>)

### 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [24]:
# using tensor from question 6
# can use either tf.newaxis or tf.expand_dims()
random_d = random_c[tf.newaxis, ...]
random_d

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float32, numpy=
array([[[[-0.7565803 , -0.06854702,  0.07595026],
         [-1.2573844 , -0.23193763, -1.8107855 ],
         [ 0.09988727, -0.50998646, -0.7535805 ],
         ...,
         [ 0.07099114, -0.5095768 ,  0.3482001 ],
         [ 0.15985982, -1.9042184 ,  0.9690504 ],
         [ 0.16251186, -0.07330752, -0.360591  ]],

        [[ 0.18739441, -0.73353654,  1.2104433 ],
         [ 1.5603006 , -0.48115277,  0.6335167 ],
         [-0.5612103 ,  0.06994031,  1.6807095 ],
         ...,
         [-1.9460293 , -0.7977275 ,  0.03092833],
         [ 0.8297488 ,  0.12179119,  1.0506107 ],
         [-1.3097638 ,  0.92536974, -1.1787732 ]],

        [[-0.21711822, -0.73974085, -1.3077081 ],
         [-0.7502274 , -0.37715855, -0.30130875],
         [ 1.0943383 ,  0.255803  ,  0.8011465 ],
         ...,
         [-0.32833767, -0.7794747 ,  0.20049338],
         [-0.09002841,  0.07243238, -0.81940895],
         [ 0.3171264 , -1.6143695 , -1.6824651

In [25]:
tf.squeeze(random_d)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535805 ],
        ...,
        [ 0.07099114, -0.5095768 ,  0.3482001 ],
        [ 0.15985982, -1.9042184 ,  0.9690504 ],
        [ 0.16251186, -0.07330752, -0.360591  ]],

       [[ 0.18739441, -0.73353654,  1.2104433 ],
        [ 1.5603006 , -0.48115277,  0.6335167 ],
        [-0.5612103 ,  0.06994031,  1.6807095 ],
        ...,
        [-1.9460293 , -0.7977275 ,  0.03092833],
        [ 0.8297488 ,  0.12179119,  1.0506107 ],
        [-1.3097638 ,  0.92536974, -1.1787732 ]],

       [[-0.21711822, -0.73974085, -1.3077081 ],
        [-0.7502274 , -0.37715855, -0.30130875],
        [ 1.0943383 ,  0.255803  ,  0.8011465 ],
        ...,
        [-0.32833767, -0.7794747 ,  0.20049338],
        [-0.09002841,  0.07243238, -0.81940895],
        [ 0.3171264 , -1.6143695 , -1.6824651 ]],

       ...,

     

### 9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [29]:
random_tensor = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tf.argmax(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=9>

### 10. One-hot encode the tensor you created in 9.

In [34]:
# one-hot encoding starts from 0, but my list starts from 1, hence set depth = 11 to see the full one-hot encoding
tf.one_hot(random_tensor, depth = 11)

<tf.Tensor: shape=(10, 11), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>

## 📖 Extra-curriculum

- Read through the list of [TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
- Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
    - How would you calculate your grocery bill for the month and for the year using tensors?
- Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
    - Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
- Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.